version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: date-fns
        versions:
          - 2.18.0
          - 2.19.0
          - 2.20.0
          - 2.20.1
          - 2.20.2
          - 2.20.3
      - dependency-name: recoil
        versions:
          - 0.1.3
      - dependency-name: date-fns-tz
        versions:
          - 1.1.2
          - 1.1.3
      - dependency-name: react-scripts
        versions:
          - 4.0.1
          - 4.0.2
      - dependency-name: moment-timezone
        versions:
          - 0.5.32
          - 0.5.33
